---

- name: install epel-release
  yum: name=epel-release state=latest

- name: install nginx
  yum: name=nginx state=latest

- name: install pip 
  yum: name=python-pip state=latest

- name: install passlib
  pip: name=passlib

- name: set passwd for web login
  htpasswd: path=/etc/nginx/passwd name={{ user_name }} password={{ user_pass }} owner=root group=root mode=0640

- name: copy default conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: restart service nginx
  service: name=nginx enabled=yes state=restarted


